// src/pages/tickets/TicketDetails.vue
<template>
  <main class="ticket-detail container">
    <template v-if="!ticket">
      <p>{{ message || 'Loading ticket...' }}</p>
    </template>

    <template v-else>
      <header class="ticket-detail-header">
        <h1>{{ ticket.title }}</h1>
        <span :class="['status-tag', ticket.status.toLowerCase()]">
          {{ ticket.status }}
        </span>
      </header>

      <section class="ticket-detail-body">
        <p class="ticket-description">{{ ticket.description }}</p>

        <div class="ticket-meta">
          <small>
            Created: {{ formatDateTime(ticket.createdAt) }} <br />
            Last Updated: {{ formatDateTime(ticket.updatedAt) }}
          </small>
        </div>
      </section>

      <footer class="ticket-detail-actions">
        <button
          @click="$router.push(`/tickets/edit/${ticket.id}`)"
          class="btn btn-edit"
        >
          Edit
        </button>
        <button @click="handleDelete" class="btn btn-delete">
          Delete
        </button>
        <button @click="$router.push('/tickets')" class="btn btn-secondary">
          Back to List
        </button>
      </footer>

      <p v-if="message" class="feedback success">{{ message }}</p>
    </template>
  </main>
</template>

<script>
import { ref, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { getTicketById, deleteTicket } from '../../utils/storage'
import { isAuthenticated } from '../../utils/auth'

export default {
  name: 'TicketDetail',
  setup() {
    const router = useRouter()
    const route = useRoute()
    const ticket = ref(null)
    const message = ref('')

    onMounted(() => {
      if (!isAuthenticated()) {
        router.push('/auth/login')
        return
      }

      const data = getTicketById(route.params.id)
      if (!data) {
        message.value = '⚠️ Ticket not found.'
        setTimeout(() => {
          router.push('/tickets')
        }, 2000)
      } else {
        ticket.value = data
      }
    })

    const handleDelete = () => {
      if (window.confirm('Are you sure you want to delete this ticket?')) {
        deleteTicket(Number(route.params.id))
        message.value = '✅ Ticket deleted successfully!'
        setTimeout(() => {
          router.push('/tickets')
        }, 1200)
      }
    }

    const formatDateTime = (date) => {
      return new Date(date).toLocaleString()
    }

    return {
      ticket,
      message,
      handleDelete,
      formatDateTime
    }
  }
}
</script>

<style scoped src="../../styles/ticketDetails.css"></style>

// src/pages/tickets/TicketDetails.jsx
import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { getTicketById, deleteTicket } from "../../utils/storage";
import { isAuthenticated } from "../../utils/auth";
import "../../styles/ticketDetails.css";

export default function TicketDetail() {
  const navigate = useNavigate();
  const { id } = useParams();
  const [ticket, setTicket] = useState(null);
  const [message, setMessage] = useState("");

  useEffect(() => {
    if (!isAuthenticated()) {
      navigate("/login");
      return;
    }

    const data = getTicketById(id);
    if (!data) {
      setMessage("⚠️ Ticket not found.");
      setTimeout(() => navigate("/tickets"), 2000);
    } else {
      setTicket(data);
    }
  }, [id, navigate]);

  const handleDelete = () => {
    if (window.confirm("Are you sure you want to delete this ticket?")) {
      deleteTicket(Number(id));
      setMessage("✅ Ticket deleted successfully!");
      setTimeout(() => navigate("/tickets"), 1200);
    }
  };

  if (!ticket)
    return (
      <main className="ticket-detail container">
        <p>{message || "Loading ticket..."}</p>
      </main>
    );

  return (
    <main className="ticket-detail container">
      <header className="ticket-detail-header">
        <h1>{ticket.title}</h1>
        <span className={`status-tag ${ticket.status.toLowerCase()}`}>
          {ticket.status}
        </span>
      </header>

      <section className="ticket-detail-body">
        <p className="ticket-description">{ticket.description}</p>

        <div className="ticket-meta">
          <small>
            Created: {new Date(ticket.createdAt).toLocaleString()} <br />
            Last Updated: {new Date(ticket.updatedAt).toLocaleString()}
          </small>
        </div>
      </section>

      <footer className="ticket-detail-actions">
        <button
          onClick={() => navigate(`/tickets/edit/${ticket.id}`)}
          className="btn btn-edit"
        >
          Edit
        </button>
        <button onClick={handleDelete} className="btn btn-delete">
          Delete
        </button>
        <button onClick={() => navigate("/tickets")} className="btn btn-secondary">
          Back to List
        </button>
      </footer>

      {message && <p className="feedback success">{message}</p>}
    </main>
  );
}
