// src/pages/tickets/TicketEdit.vue
<template>
  <main class="ticket-edit container">
    <template v-if="!ticket">
      <p>{{ message || 'Loading ticket...' }}</p>
    </template>

    <template v-else>
      <header class="ticket-edit-header">
        <h2>Edit Ticket</h2>
        <button @click="$router.push('/tickets')" class="btn btn-secondary">
          ← Back
        </button>
      </header>

      <form class="ticket-form" @submit.prevent="handleSubmit">
        <div class="form-group">
          <label for="title">Title</label>
          <input
            id="title"
            name="title"
            v-model="form.title"
            placeholder="Enter ticket title"
          />
        </div>

        <div class="form-group">
          <label for="description">Description</label>
          <textarea
            id="description"
            name="description"
            v-model="form.description"
            placeholder="Describe the issue"
          />
        </div>

        <div class="form-group">
          <label for="status">Status</label>
          <select
            id="status"
            name="status"
            v-model="form.status"
          >
            <option value="Open">Open</option>
            <option value="In Progress">In Progress</option>
            <option value="Resolved">Resolved</option>
          </select>
        </div>

        <div class="form-group">
          <label for="priority">Priority</label>
          <select
            id="priority"
            name="priority"
            v-model="form.priority"
          >
            <option value="Low">Low</option>
            <option value="Medium">Medium</option>
            <option value="High">High</option>
          </select>
        </div>

        <p v-if="message" class="form-message">{{ message }}</p>

        <button type="submit" class="btn btn-primary">
          Save Changes
        </button>
      </form>
    </template>
  </main>
</template>

<script>
import { ref, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { isAuthenticated } from '../../utils/auth'
import { getTicketById, updateTicket } from '../../utils/storage'

export default {
  name: 'EditTicketPage',
  setup() {
    const router = useRouter()
    const route = useRoute()
    const ticket = ref(null)
    const form = ref({
      title: '',
      description: '',
      status: 'Open',
      priority: 'Medium'
    })
    const message = ref('')

    onMounted(() => {
      if (!isAuthenticated()) {
        router.push('/auth/login')
        return
      }
      const data = getTicketById(route.params.id)
      if (!data) {
        message.value = '⚠️Ticket not found. Redirecting...'
        setTimeout(() => {
          router.push('/tickets')
        }, 2000)
      } else {
        ticket.value = data
        form.value = {
          title: data.title,
          description: data.description,
          status: data.status,
          priority: data.priority
        }
        message.value = ''
      }
    })

    const handleSubmit = () => {
      if (!form.value.title.trim() || !form.value.description.trim()) {
        message.value = '❌ Title and description are required.'
        return
      }

      try {
        updateTicket(route.params.id, form.value)
        message.value = '✅ Ticket updated successfully!'
        setTimeout(() => {
          router.push('/tickets')
        }, 1500)
      } catch (err) {
        message.value = '❌ ' + err.message
      }
    }

    return {
      ticket,
      form,
      message,
      handleSubmit
    }
  }
}
</script>

<style scoped src="../../styles/ticketEdit.css"></style>

// src/pages/tickets/TicketEdit.jsx
import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { isAuthenticated } from "../../utils/auth";
import { getTicketById, updateTicket } from "../../utils/storage";
import "../../styles/ticketEdit.css";

export default function EditTicketPage() {
  const navigate = useNavigate();
  const { id } = useParams();

  const [ticket, setTicket] = useState(null);
  const [form, setForm] = useState({
    title: "",
    description: "",
    status: "Open",
    priority: "Medium",
  });
  const [message, setMessage] = useState("");

  // ✅ Load ticket data
  useEffect(() => {
    if (!isAuthenticated()) {
      navigate("/login");
      return;
    }
    const data = getTicketById(id);
    if (!data) {
      setMessage("⚠️Ticket not found. Redirecting...");
      setTimeout(() => navigate("/tickets"), 2000);
    } else {
      setTicket(data);
      setForm({
        title: data.title,
        description: data.description,
        status: data.status,
        priority: data.priority,
      });
      setMessage("")
    }
  }, [id, navigate]);

  // ✅ Handle form input
  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  // ✅ Validate + Update ticket
  const handleSubmit = (e) => {
    e.preventDefault();
    if (!form.title.trim() || !form.description.trim()) {
      setMessage("❌ Title and description are required.");
      return;
    }

    try {
      updateTicket(id, form);
      setMessage("✅ Ticket updated successfully!");
      setTimeout(() => navigate("/tickets"), 1500);
    } catch (err) {
      setMessage("❌ " + err.message);
    }
  };

  if (!ticket) {
    return (
      <main className="ticket-edit container">
        <p>{message || "Loading ticket..."}</p>
      </main>
    );
  }

  return (
    <main className="ticket-edit container">
      <header className="ticket-edit-header">
        <h2>Edit Ticket</h2>
        <button onClick={() => navigate("/tickets")} className="btn btn-secondary">
          ← Back
        </button>
      </header>

      <form className="ticket-form" onSubmit={handleSubmit}>
        <div className="form-group">
          <label htmlFor="title">Title</label>
          <input
            id="title"
            name="title"
            value={form.title}
            onChange={handleChange}
            placeholder="Enter ticket title"
          />
        </div>

        <div className="form-group">
          <label htmlFor="description">Description</label>
          <textarea
            id="description"
            name="description"
            value={form.description}
            onChange={handleChange}
            placeholder="Describe the issue"
          />
        </div>

        <div className="form-group">
          <label htmlFor="status">Status</label>
          <select
            id="status"
            name="status"
            value={form.status}
            onChange={handleChange}
          >
            <option value="Open">Open</option>
            <option value="In Progress">In Progress</option>
            <option value="Resolved">Resolved</option>
          </select>
        </div>

        <div className="form-group">
          <label htmlFor="priority">Priority</label>
          <select
            id="priority"
            name="priority"
            value={form.priority}
            onChange={handleChange}
          >
            <option value="Low">Low</option>
            <option value="Medium">Medium</option>
            <option value="High">High</option>
          </select>
        </div>

        {message && <p className="form-message">{message}</p>}

        <button type="submit" className="btn btn-primary">
          Save Changes
        </button>
      </form>
    </main>
  );
}
