// src/components/Navbar.jsx
import React from "react";
import { Link, useLocation } from "react-router-dom";
import "../styles/navbar.css";

export default function Navbar() {
  const location = useLocation();

  return (
    <header className="navbar">
      <nav className="navbar-container">
        <div className="navbar-logo">
          <Link to="/" aria-label="Go to home page">
            🎫 Ticket Manager Pro
          </Link>
        </div>

        <ul className="navbar-links">
          <li>
            <Link
              to="/"
              className={location.pathname === "/" ? "active" : ""}
            >
              Home
            </Link>
          </li>
          <li>
            <Link
              to="/auth/login"
              className={location.pathname.includes("/auth/login") ? "active" : ""}
            >
              Login
            </Link>
          </li>
          <li>
            <Link
              to="/auth/signup"
              className={location.pathname.includes("/auth/signup") ? "active" : ""}
            >
              Signup
            </Link>
          </li>
        </ul>
      </nav>
    </header>
  );
}

// src/components/Navbar.vue
<template>
  <header class="navbar">
    <nav class="navbar-container">
      <div class="navbar-logo">
        <router-link to="/" aria-label="Go to home page">
          🎫 Ticket Manager Pro
        </router-link>
      </div>

      <ul class="navbar-links">
        <li>
          <router-link to="/" :class="{ active: $route.path === '/' }">
            Home
          </router-link>
        </li>
        <li>
          <router-link
            to="/auth/login"
            :class="{ active: $route.path.includes('/auth/login') }"
          >
            Login
          </router-link>
        </li>
        <li>
          <router-link
            to="/auth/signup"
            :class="{ active: $route.path.includes('/auth/signup') }"
          >
            Signup
          </router-link>
        </li>
      </ul>
    </nav>
  </header>
</template>

<script>
export default {
  name: 'Navbar'
}
</script>

<style scoped src="../styles/navbar.css"></style>
